- patt: [tests/.*]
  exclude: true
- patt: [package.js]
  exclude: true
- patt: [(\A|\.+/)\.gitignore]
  exclude: true
- patt: [lib/common/.*]
  client: true
  server: true
- patt: [lib/client/.*]
  client: true
- patt: [lib/server/.*]
  server: true
- patt: [methods/common/.*]
  client: true
  server: true
- patt: [methods/client/.*]
  client: true
- patt: [methods/server/.*, publications/.*]
  server: true
- patt:
    - style/.*
    - components/.*\.(less|css)
    - layout-yields/.*\.(less|css)
    - layouts/.*\.(less|css)
    - modal/.*\.(less|css)
    - pages/.*\.(less|css)
    - components/.*\.html
    - layout-yields/.*\.html
    - layouts/.*\.html
    - modal/.*\.html
    - pages/.*\.html
    - components/.*\.(js|jsx|coffee)
    - layout-yields/.*\.(js|jsx|coffee)
    - layouts/.*\.(js|jsx|coffee)
    - modal/.*\.(js|jsx|coffee)
    - pages/.*\.(js|jsx|coffee)
  client: true
- patt: [routes/.*]
  client: true
  server: true
- patt: [routes-server/.*]
  server: true
- patt: [routes-client/.*]
  client: true
- patt: [images/.*]
  asset: true
  client: true
- patt: [assets/.*]
  asset: true
  client: true
  server: true
